version: '3.8'

services:
  go-app:
    image: venukishore/go_health_check-go-app:1.0.0
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 2s
      retries: 3
